# Generated by Django 4.1.7 on 2023-02-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='video',
            field=models.FileField(blank=True, default=1, upload_to='videos_uploaded'),
            preserve_default=False,
        ),
    ]
