# Generated by Django 4.1.7 on 2023-02-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmedia_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='description_for_alt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
