# Generated by Django 4.1.7 on 2023-03-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
