# Generated by Django 4.1.7 on 2023-03-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_page_html',
            field=models.TextField(default=''),
        ),
    ]
