# Generated by Django 4.1.7 on 2023-03-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_description_page_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('main_url', models.TextField(blank=True)),
                ('stock_indicator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('verification_url', models.CharField(blank=True, max_length=200)),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('display_image', models.ImageField(blank=True, upload_to='')),
                ('company', models.ManyToManyField(to='projects.company', verbose_name='Creator Company')),
            ],
        ),
    ]
