# Generated by Django 4.1.7 on 2023-03-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_company_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='hosted_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
