# Generated by Django 4.1.7 on 2023-09-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_github_url_project_hosted_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='is_logo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_page_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
