import NEXTHead from "next/head"

export const Head = (props:{children?:React.ReactNode[]}) => {
    return <div>
    <NEXTHead>
        <title>xxparthparekhxx</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </NEXTHead>
    {props.children}
    </div>
}